---
# Common Role - Meta Information

galaxy_info:
  author: VMStation Team
  description: Common base configuration for all cluster hosts
  license: MIT
  min_ansible_version: "2.9"
  platforms:
    - name: Debian
      versions:
        - bullseye
        - bookworm
    - name: EL
      versions:
        - "8"
        - "9"
        - "10"
  galaxy_tags:
    - system
    - common
    - baseline

dependencies: []
