---
# NTP Role - Meta Information

galaxy_info:
  author: VMStation Team
  description: NTP/Chrony time synchronization configuration
  license: MIT
  min_ansible_version: "2.9"
  platforms:
    - name: Debian
      versions:
        - bullseye
        - bookworm
    - name: EL
      versions:
        - "8"
        - "9"
        - "10"
  galaxy_tags:
    - ntp
    - chrony
    - time
    - synchronization

dependencies:
  - role: common
