---
# Kerberos Role - Meta Information

galaxy_info:
  author: VMStation Team
  description: Kerberos authentication configuration
  license: MIT
  min_ansible_version: "2.9"
  platforms:
    - name: Debian
      versions:
        - bullseye
        - bookworm
    - name: EL
      versions:
        - "8"
        - "9"
        - "10"
  galaxy_tags:
    - kerberos
    - authentication
    - security
    - sssd

dependencies:
  - role: common
  - role: ntp  # Kerberos requires accurate time
